### ISSUE TITLE
Подготовить список функций ПО. Создать начальное приложение сайта на Django

### ISSUE THREAD

**Issue by TenkachevaDaria** [TenkachevaDaria/Djando_prodject_-#1]
Срок: 23.03.2024

**Comment by KiTKaT2034** [comment]
оплата
корзина
регистрация
фильтр товаров
история покупок
поиск по названию
связь с тех поддержкой
отправка чеков пользователю
редактирование пользователя
возможность добавлять свой товар
возможность добавлять товар в избранное
возможность оценивать и комментировать
возможность добавить несколько способов оплаты

**Comment by KiTKaT2034** [comment]
[Отчёт по функционалу сайта.docx](https://github.com/TenkachevaDaria/Djando_prodject_-/files/14650160/default.docx)

**Comment by KiTKaT2034** [comment]
[PROJECT.zip](https://github.com/TenkachevaDaria/Djando_prodject_-/files/14650177/PROJECT.zip)
