### ISSUE TITLE
Подготовить обзор подобных задач

### ISSUE THREAD

**Issue by TenkachevaDaria** [TenkachevaDaria/Djando_prodject_-#2]
Срок: 23.03.2024

**Comment by nastyuxxxa** [comment]
[Обзор подобных задач.docx](https://github.com/TenkachevaDaria/Djando_prodject_-/files/14640833/default.docx)

**Comment by nastyuxxxa** [comment]
[Обзор подобных задач(изменённая версия).docx](https://github.com/TenkachevaDaria/Djando_prodject_-/files/14815973/default.docx)
