### ISSUE TITLE
Подготовить эскиз сайта (без напонения)

### ISSUE THREAD

**Issue by TenkachevaDaria** [TenkachevaDaria/Djando_prodject_-#3]
Срок: 23.03.2024

**Comment by dashuulka** [comment]
![аккаунт(не все поля заполнены)](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/7c93c073-2dbc-4900-9f75-69e67c405f64)
![все товары (с фильтрами)](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/020a022f-cca9-41a6-95e7-0622472a3e05)
![вход](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/ed6d832e-1da4-4db6-95ee-b1cd49e78283)
![главная страницаееееее](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/a4db4fcd-e7eb-440a-bedb-aa8bb9370c8d)
![карточка товара](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/46556c9a-977b-4508-a748-ba2ddf21918e)
![корзина](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/fa11a9d6-51c3-416d-983d-3150ced633da)
![рега](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/77d1efa7-6724-457c-96f3-91258e24c4a7)
![форма добавления товара](https://github.com/TenkachevaDaria/Djando_prodject_-/assets/128921791/09a6b58c-d3bb-4b5a-a4cb-080cd8cb89b1)
