### ISSUE TITLE
Спроектировать начальный интерфейс для сайта (HTML, CSS...)

### ISSUE THREAD

**Issue by TenkachevaDaria** [TenkachevaDaria/Djando_prodject_-#5]
Срок: 23.03.2024

**Comment by Fugel7** [comment]
[https://drive.google.com/file/d/1b3msquTVk6gHffg22v5CMUXAgaJKb2cp/view?usp=drive_link](https://vk.com/away.php?to=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1b3msquTVk6gHffg22v5CMUXAgaJKb2cp%2Fview%3Fusp%3Ddrive_link&cc_key=) - ссылка на видеодемонстрацию первоначальной вёрстки

**Comment by Fugel7** [comment]
https://github.com/TenkachevaDaria/Djando_prodject_-/commit/1ea7c06f1695dccc205ebb7e365df33d49670baa - ссылка на 1ый commit
